package de.idv.skiller.beans;
// Generated 06.06.2016 19:00:14 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Priority generated by hbm2java
 */
@Entity
@Table(name="PRIORITY"
    ,schema="PUBLIC"
    ,catalog="SKILLER"
)
public class Priority  implements java.io.Serializable {


     private Integer id;
     private Skill skill;
     private Request request;
     private String value;

    public Priority() {
    }

    public Priority(Skill skill, Request request, String value) {
       this.skill = skill;
       this.request = request;
       this.value = value;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SKILL", nullable=false)
    public Skill getSkill() {
        return this.skill;
    }
    
    public void setSkill(Skill skill) {
        this.skill = skill;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="REQUEST", nullable=false)
    public Request getRequest() {
        return this.request;
    }
    
    public void setRequest(Request request) {
        this.request = request;
    }
    
    @Column(name="VALUE", nullable=false)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


