package de.idv.skiller.beans;
// Generated 06.06.2016 19:00:14 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rating generated by hbm2java
 */
@Entity
@Table(name="RATING"
    ,schema="PUBLIC"
    ,catalog="SKILLER"
)
public class Rating  implements java.io.Serializable {


     private Integer id;
     private Skill skill;
     private Party party;
     private String duration;

    public Rating() {
    }

    public Rating(Skill skill, Party party, String duration) {
       this.skill = skill;
       this.party = party;
       this.duration = duration;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SKILL", nullable=false)
    public Skill getSkill() {
        return this.skill;
    }
    
    public void setSkill(Skill skill) {
        this.skill = skill;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PARTY", nullable=false)
    public Party getParty() {
        return this.party;
    }
    
    public void setParty(Party party) {
        this.party = party;
    }
    
    @Column(name="DURATION", nullable=false)
    public String getDuration() {
        return this.duration;
    }
    
    public void setDuration(String duration) {
        this.duration = duration;
    }




}


