package de.idv.skiller.beans;
// Generated 06.06.2016 19:00:14 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Skill generated by hbm2java
 */
@Entity
@Table(name="SKILL"
    ,schema="PUBLIC"
    ,catalog="SKILLER"
)
public class Skill  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private Set<Rating> ratings = new HashSet<Rating>(0);
     private Set<Project> projects = new HashSet<Project>(0);
     private Set<Priority> priorities = new HashSet<Priority>(0);

    public Skill() {
    }

	
    public Skill(String name, String description) {
        this.name = name;
        this.description = description;
    }
    public Skill(String name, String description, Set<Rating> ratings, Set<Project> projects, Set<Priority> priorities) {
       this.name = name;
       this.description = description;
       this.ratings = ratings;
       this.projects = projects;
       this.priorities = priorities;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="NAME", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="DESCRIPTION", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="skill")
    public Set<Rating> getRatings() {
        return this.ratings;
    }
    
    public void setRatings(Set<Rating> ratings) {
        this.ratings = ratings;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="PROJECT_SKILL", schema="PUBLIC", catalog="SKILLER", joinColumns = { 
        @JoinColumn(name="SKILL", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="PROJECT", nullable=false, updatable=false) })
    public Set<Project> getProjects() {
        return this.projects;
    }
    
    public void setProjects(Set<Project> projects) {
        this.projects = projects;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="skill")
    public Set<Priority> getPriorities() {
        return this.priorities;
    }
    
    public void setPriorities(Set<Priority> priorities) {
        this.priorities = priorities;
    }




}


