package org.anonymous.project;
// Generated 14.11.2015 00:32:01 by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="ACCOUNT"
    ,catalog="PUBLIC"
)
public class Account  implements java.io.Serializable {


     private int id;
     private String name;
     private String bic;
     private String iban;

    public Account() {
    }

    public Account(int id, String name, String bic, String iban) {
       this.id = id;
       this.name = name;
       this.bic = bic;
       this.iban = iban;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAME", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="BIC", nullable=false, length=12)
    public String getBic() {
        return this.bic;
    }
    
    public void setBic(String bic) {
        this.bic = bic;
    }

    
    @Column(name="IBAN", nullable=false, length=22)
    public String getIban() {
        return this.iban;
    }
    
    public void setIban(String iban) {
        this.iban = iban;
    }




}


