package org.anonymous.project;
// Generated 04.10.2019 09:31:23 by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="ACCOUNT"
    ,catalog="PUBLIC"
)
public class Account  implements java.io.Serializable {


     private int id;
     private String name;
     private String bic;
     private String iban;
     private Set<Discharge> discharges = new HashSet<Discharge>(0);

    public Account() {
    }

	
    public Account(int id, String name, String bic, String iban) {
        this.id = id;
        this.name = name;
        this.bic = bic;
        this.iban = iban;
    }
    public Account(int id, String name, String bic, String iban, Set<Discharge> discharges) {
       this.id = id;
       this.name = name;
       this.bic = bic;
       this.iban = iban;
       this.discharges = discharges;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAME", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="BIC", nullable=false, length=12)
    public String getBic() {
        return this.bic;
    }
    
    public void setBic(String bic) {
        this.bic = bic;
    }

    
    @Column(name="IBAN", nullable=false, length=22)
    public String getIban() {
        return this.iban;
    }
    
    public void setIban(String iban) {
        this.iban = iban;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="account")
    public Set<Discharge> getDischarges() {
        return this.discharges;
    }
    
    public void setDischarges(Set<Discharge> discharges) {
        this.discharges = discharges;
    }




}


