package org.anonymous.project;
// Generated 14.11.2015 00:32:01 by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name="ADDRESS"
    ,catalog="PUBLIC"
)
public class Address  implements java.io.Serializable {


     private int id;
     private String street;
     private String code;
     private String city;
     private String country;

    public Address() {
    }

    public Address(int id, String street, String code, String city, String country) {
       this.id = id;
       this.street = street;
       this.code = code;
       this.city = city;
       this.country = country;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="STREET", nullable=false, length=64)
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="CODE", nullable=false, length=64)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="CITY", nullable=false, length=64)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="COUNTRY", nullable=false, length=64)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }




}


