package org.anonymous.project;
// Generated 27.11.2015 18:21:32 by Hibernate Tools 4.3.1.Final


import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="CATEGORY"
    ,catalog="PUBLIC"
)
public class Category  implements java.io.Serializable {


     private int id;
     private String name;
     private Blob icon;
     private Set<Area> areas = new HashSet<Area>(0);

    public Category() {
    }

	
    public Category(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Category(int id, String name, Blob icon, Set<Area> areas) {
       this.id = id;
       this.name = name;
       this.icon = icon;
       this.areas = areas;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAME", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="ICON")
    public Blob getIcon() {
        return this.icon;
    }
    
    public void setIcon(Blob icon) {
        this.icon = icon;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<Area> getAreas() {
        return this.areas;
    }
    
    public void setAreas(Set<Area> areas) {
        this.areas = areas;
    }




}


