package org.anonymous.project;
// Generated 14.11.2015 00:32:01 by Hibernate Tools 4.3.1.Final


import java.sql.Blob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="CATEGORY"
    ,catalog="PUBLIC"
)
public class Category  implements java.io.Serializable {


     private int id;
     private String name;
     private Blob icon;

    public Category() {
    }

	
    public Category(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Category(int id, String name, Blob icon) {
       this.id = id;
       this.name = name;
       this.icon = icon;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAME", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="ICON")
    public Blob getIcon() {
        return this.icon;
    }
    
    public void setIcon(Blob icon) {
        this.icon = icon;
    }




}


