package org.anonymous.project;
// Generated 14.11.2015 00:32:01 by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Chargeitem generated by hbm2java
 */
@Entity
@Table(name="CHARGEITEM"
    ,catalog="PUBLIC"
)
public class Chargeitem  implements java.io.Serializable {


     private int id;
     private int charge;
     private int item;

    public Chargeitem() {
    }

    public Chargeitem(int id, int charge, int item) {
       this.id = id;
       this.charge = charge;
       this.item = item;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="CHARGE", nullable=false)
    public int getCharge() {
        return this.charge;
    }
    
    public void setCharge(int charge) {
        this.charge = charge;
    }

    
    @Column(name="ITEM", nullable=false)
    public int getItem() {
        return this.item;
    }
    
    public void setItem(int item) {
        this.item = item;
    }




}


