package org.anonymous.project;
// Generated 27.11.2015 18:21:32 by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chargeitem generated by hbm2java
 */
@Entity
@Table(name="CHARGEITEM"
    ,catalog="PUBLIC"
)
public class Chargeitem  implements java.io.Serializable {


     private int id;
     private Item item;
     private int charge;
     private Set<Charge> charges = new HashSet<Charge>(0);

    public Chargeitem() {
    }

	
    public Chargeitem(int id, Item item, int charge) {
        this.id = id;
        this.item = item;
        this.charge = charge;
    }
    public Chargeitem(int id, Item item, int charge, Set<Charge> charges) {
       this.id = id;
       this.item = item;
       this.charge = charge;
       this.charges = charges;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM", nullable=false)
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }

    
    @Column(name="CHARGE", nullable=false)
    public int getCharge() {
        return this.charge;
    }
    
    public void setCharge(int charge) {
        this.charge = charge;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="chargeitem")
    public Set<Charge> getCharges() {
        return this.charges;
    }
    
    public void setCharges(Set<Charge> charges) {
        this.charges = charges;
    }




}


