package org.anonymous.project;
// Generated 04.10.2019 09:31:23 by Hibernate Tools 4.3.1.Final


import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chargestatus generated by hbm2java
 */
@Entity
@Table(name="CHARGESTATUS"
    ,catalog="PUBLIC"
)
public class Chargestatus  implements java.io.Serializable {


     private int id;
     private String name;
     private String description;
     private Blob icon;
     private Set<Charge> charges = new HashSet<Charge>(0);

    public Chargestatus() {
    }

	
    public Chargestatus(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Chargestatus(int id, String name, String description, Blob icon, Set<Charge> charges) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.icon = icon;
       this.charges = charges;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAME", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="DESCRIPTION", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="ICON")
    public Blob getIcon() {
        return this.icon;
    }
    
    public void setIcon(Blob icon) {
        this.icon = icon;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="chargestatus")
    public Set<Charge> getCharges() {
        return this.charges;
    }
    
    public void setCharges(Set<Charge> charges) {
        this.charges = charges;
    }




}


