package org.anonymous.project;
// Generated 14.11.2015 00:32:01 by Hibernate Tools 4.3.1.Final


import java.sql.Blob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Classification generated by hbm2java
 */
@Entity
@Table(name="CLASSIFICATION"
    ,catalog="PUBLIC"
)
public class Classification  implements java.io.Serializable {


     private int id;
     private int value;
     private String name;
     private Blob icon;

    public Classification() {
    }

	
    public Classification(int id, int value, String name) {
        this.id = id;
        this.value = value;
        this.name = name;
    }
    public Classification(int id, int value, String name, Blob icon) {
       this.id = id;
       this.value = value;
       this.name = name;
       this.icon = icon;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="VALUE", nullable=false)
    public int getValue() {
        return this.value;
    }
    
    public void setValue(int value) {
        this.value = value;
    }

    
    @Column(name="NAME", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="ICON")
    public Blob getIcon() {
        return this.icon;
    }
    
    public void setIcon(Blob icon) {
        this.icon = icon;
    }




}


