package org.anonymous.project;
// Generated 04.10.2019 09:31:23 by Hibernate Tools 4.3.1.Final


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Coordinate generated by hbm2java
 */
@Entity
@Table(name="COORDINATE"
    ,catalog="PUBLIC"
)
public class Coordinate  implements java.io.Serializable {


     private int id;
     private BigDecimal x;
     private BigDecimal y;
     private BigDecimal z;
     private Set<Location> locations = new HashSet<Location>(0);

    public Coordinate() {
    }

	
    public Coordinate(int id, BigDecimal x, BigDecimal y) {
        this.id = id;
        this.x = x;
        this.y = y;
    }
    public Coordinate(int id, BigDecimal x, BigDecimal y, BigDecimal z, Set<Location> locations) {
       this.id = id;
       this.x = x;
       this.y = y;
       this.z = z;
       this.locations = locations;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="X", nullable=false, precision=65535, scale=32767)
    public BigDecimal getX() {
        return this.x;
    }
    
    public void setX(BigDecimal x) {
        this.x = x;
    }

    
    @Column(name="Y", nullable=false, precision=65535, scale=32767)
    public BigDecimal getY() {
        return this.y;
    }
    
    public void setY(BigDecimal y) {
        this.y = y;
    }

    
    @Column(name="Z", precision=65535, scale=32767)
    public BigDecimal getZ() {
        return this.z;
    }
    
    public void setZ(BigDecimal z) {
        this.z = z;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="coordinate")
    public Set<Location> getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set<Location> locations) {
        this.locations = locations;
    }




}


