package org.anonymous.project;
// Generated 14.11.2015 00:32:01 by Hibernate Tools 4.3.1.Final


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Coordinate generated by hbm2java
 */
@Entity
@Table(name="COORDINATE"
    ,catalog="PUBLIC"
)
public class Coordinate  implements java.io.Serializable {


     private int id;
     private BigDecimal x;
     private BigDecimal y;
     private BigDecimal z;

    public Coordinate() {
    }

	
    public Coordinate(int id, BigDecimal x, BigDecimal y) {
        this.id = id;
        this.x = x;
        this.y = y;
    }
    public Coordinate(int id, BigDecimal x, BigDecimal y, BigDecimal z) {
       this.id = id;
       this.x = x;
       this.y = y;
       this.z = z;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="X", nullable=false, precision=128, scale=0)
    public BigDecimal getX() {
        return this.x;
    }
    
    public void setX(BigDecimal x) {
        this.x = x;
    }

    
    @Column(name="Y", nullable=false, precision=128, scale=0)
    public BigDecimal getY() {
        return this.y;
    }
    
    public void setY(BigDecimal y) {
        this.y = y;
    }

    
    @Column(name="Z", precision=128, scale=0)
    public BigDecimal getZ() {
        return this.z;
    }
    
    public void setZ(BigDecimal z) {
        this.z = z;
    }




}


