package org.anonymous.project;
// Generated 14.11.2015 00:32:01 by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Digital generated by hbm2java
 */
@Entity
@Table(name="DIGITAL"
    ,catalog="PUBLIC"
)
public class Digital  implements java.io.Serializable {


     private int id;
     private int location;
     private String name;
     private String value;

    public Digital() {
    }

    public Digital(int id, int location, String name, String value) {
       this.id = id;
       this.location = location;
       this.name = name;
       this.value = value;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="LOCATION", nullable=false)
    public int getLocation() {
        return this.location;
    }
    
    public void setLocation(int location) {
        this.location = location;
    }

    
    @Column(name="NAME", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="VALUE", nullable=false, length=64)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


