package org.anonymous.project;
// Generated 14.11.2015 00:32:01 by Hibernate Tools 4.3.1.Final


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Discharge generated by hbm2java
 */
@Entity
@Table(name="DISCHARGE"
    ,catalog="PUBLIC"
)
public class Discharge  implements java.io.Serializable {


     private int id;
     private int charge;
     private int account;
     private Date date;
     private BigDecimal value;
     private String comment;
     private Blob document;

    public Discharge() {
    }

	
    public Discharge(int id, int charge, int account, Date date, BigDecimal value) {
        this.id = id;
        this.charge = charge;
        this.account = account;
        this.date = date;
        this.value = value;
    }
    public Discharge(int id, int charge, int account, Date date, BigDecimal value, String comment, Blob document) {
       this.id = id;
       this.charge = charge;
       this.account = account;
       this.date = date;
       this.value = value;
       this.comment = comment;
       this.document = document;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="CHARGE", nullable=false)
    public int getCharge() {
        return this.charge;
    }
    
    public void setCharge(int charge) {
        this.charge = charge;
    }

    
    @Column(name="ACCOUNT", nullable=false)
    public int getAccount() {
        return this.account;
    }
    
    public void setAccount(int account) {
        this.account = account;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE", nullable=false, length=26)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="VALUE", nullable=false, precision=128, scale=0)
    public BigDecimal getValue() {
        return this.value;
    }
    
    public void setValue(BigDecimal value) {
        this.value = value;
    }

    
    @Column(name="COMMENT", length=512)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    
    @Column(name="DOCUMENT")
    public Blob getDocument() {
        return this.document;
    }
    
    public void setDocument(Blob document) {
        this.document = document;
    }




}


