package org.anonymous.project;
// Generated 04.10.2019 09:31:23 by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name="LOCATION"
    ,catalog="PUBLIC"
)
public class Location  implements java.io.Serializable {


     private int id;
     private Address address;
     private Coordinate coordinate;
     private Digital digital;
     private Party party;
     private String name;
     private Set<Charge> charges = new HashSet<Charge>(0);

    public Location() {
    }

	
    public Location(int id, Digital digital, Party party, String name) {
        this.id = id;
        this.digital = digital;
        this.party = party;
        this.name = name;
    }
    public Location(int id, Address address, Coordinate coordinate, Digital digital, Party party, String name, Set<Charge> charges) {
       this.id = id;
       this.address = address;
       this.coordinate = coordinate;
       this.digital = digital;
       this.party = party;
       this.name = name;
       this.charges = charges;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ADDRESS")
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COORDINATE")
    public Coordinate getCoordinate() {
        return this.coordinate;
    }
    
    public void setCoordinate(Coordinate coordinate) {
        this.coordinate = coordinate;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DIGITAL", nullable=false)
    public Digital getDigital() {
        return this.digital;
    }
    
    public void setDigital(Digital digital) {
        this.digital = digital;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PARTY", nullable=false)
    public Party getParty() {
        return this.party;
    }
    
    public void setParty(Party party) {
        this.party = party;
    }

    
    @Column(name="NAME", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="location")
    public Set<Charge> getCharges() {
        return this.charges;
    }
    
    public void setCharges(Set<Charge> charges) {
        this.charges = charges;
    }




}


