package org.anonymous.project;
// Generated 14.11.2015 00:32:01 by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name="LOCATION"
    ,catalog="PUBLIC"
)
public class Location  implements java.io.Serializable {


     private int id;
     private String name;
     private Integer address;
     private Integer coordinate;
     private int party;
     private int digital;

    public Location() {
    }

	
    public Location(int id, String name, int party, int digital) {
        this.id = id;
        this.name = name;
        this.party = party;
        this.digital = digital;
    }
    public Location(int id, String name, Integer address, Integer coordinate, int party, int digital) {
       this.id = id;
       this.name = name;
       this.address = address;
       this.coordinate = coordinate;
       this.party = party;
       this.digital = digital;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAME", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="ADDRESS")
    public Integer getAddress() {
        return this.address;
    }
    
    public void setAddress(Integer address) {
        this.address = address;
    }

    
    @Column(name="COORDINATE")
    public Integer getCoordinate() {
        return this.coordinate;
    }
    
    public void setCoordinate(Integer coordinate) {
        this.coordinate = coordinate;
    }

    
    @Column(name="PARTY", nullable=false)
    public int getParty() {
        return this.party;
    }
    
    public void setParty(int party) {
        this.party = party;
    }

    
    @Column(name="DIGITAL", nullable=false)
    public int getDigital() {
        return this.digital;
    }
    
    public void setDigital(int digital) {
        this.digital = digital;
    }




}


