package org.anonymous.project;
// Generated 14.11.2015 00:32:01 by Hibernate Tools 4.3.1.Final


import java.sql.Blob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Organisation generated by hbm2java
 */
@Entity
@Table(name="ORGANISATION"
    ,catalog="PUBLIC"
    , uniqueConstraints = @UniqueConstraint(columnNames="NAME") 
)
public class Organisation  implements java.io.Serializable {


     private int id;
     private String name;
     private String description;
     private Blob icon;

    public Organisation() {
    }

	
    public Organisation(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Organisation(int id, String name, String description, Blob icon) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.icon = icon;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAME", unique=true, nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="DESCRIPTION", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="ICON")
    public Blob getIcon() {
        return this.icon;
    }
    
    public void setIcon(Blob icon) {
        this.icon = icon;
    }




}


