package org.anonymous.project;
// Generated 27.11.2015 18:21:32 by Hibernate Tools 4.3.1.Final


import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Organisation generated by hbm2java
 */
@Entity
@Table(name="ORGANISATION"
    ,catalog="PUBLIC"
    , uniqueConstraints = @UniqueConstraint(columnNames="NAME") 
)
public class Organisation  implements java.io.Serializable {


     private int id;
     private String name;
     private String description;
     private Blob icon;
     private Set<Item> items = new HashSet<Item>(0);
     private Set<Party> parties = new HashSet<Party>(0);
     private Set<Property> properties = new HashSet<Property>(0);

    public Organisation() {
    }

	
    public Organisation(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Organisation(int id, String name, String description, Blob icon, Set<Item> items, Set<Party> parties, Set<Property> properties) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.icon = icon;
       this.items = items;
       this.parties = parties;
       this.properties = properties;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="NAME", unique=true, nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="DESCRIPTION", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="ICON")
    public Blob getIcon() {
        return this.icon;
    }
    
    public void setIcon(Blob icon) {
        this.icon = icon;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="organisation")
    public Set<Item> getItems() {
        return this.items;
    }
    
    public void setItems(Set<Item> items) {
        this.items = items;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="organisation")
    public Set<Party> getParties() {
        return this.parties;
    }
    
    public void setParties(Set<Party> parties) {
        this.parties = parties;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="organisation")
    public Set<Property> getProperties() {
        return this.properties;
    }
    
    public void setProperties(Set<Property> properties) {
        this.properties = properties;
    }




}


