package org.anonymous.project;
// Generated 27.11.2015 18:21:32 by Hibernate Tools 4.3.1.Final


import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Party generated by hbm2java
 */
@Entity
@Table(name="PARTY"
    ,catalog="PUBLIC"
)
public class Party  implements java.io.Serializable {


     private int id;
     private Organisation organisation;
     private String name;
     private String description;
     private String shortname;
     private Blob icon;
     private Set<Location> locations = new HashSet<Location>(0);
     private Set<Property> properties = new HashSet<Property>(0);
     private Set<Charge> charges = new HashSet<Charge>(0);

    public Party() {
    }

	
    public Party(int id, Organisation organisation, String name, String shortname) {
        this.id = id;
        this.organisation = organisation;
        this.name = name;
        this.shortname = shortname;
    }
    public Party(int id, Organisation organisation, String name, String description, String shortname, Blob icon, Set<Location> locations, Set<Property> properties, Set<Charge> charges) {
       this.id = id;
       this.organisation = organisation;
       this.name = name;
       this.description = description;
       this.shortname = shortname;
       this.icon = icon;
       this.locations = locations;
       this.properties = properties;
       this.charges = charges;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORGA", nullable=false)
    public Organisation getOrganisation() {
        return this.organisation;
    }
    
    public void setOrganisation(Organisation organisation) {
        this.organisation = organisation;
    }

    
    @Column(name="NAME", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="DESCRIPTION", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="SHORTNAME", nullable=false, length=8)
    public String getShortname() {
        return this.shortname;
    }
    
    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

    
    @Column(name="ICON")
    public Blob getIcon() {
        return this.icon;
    }
    
    public void setIcon(Blob icon) {
        this.icon = icon;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="party")
    public Set<Location> getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set<Location> locations) {
        this.locations = locations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="party")
    public Set<Property> getProperties() {
        return this.properties;
    }
    
    public void setProperties(Set<Property> properties) {
        this.properties = properties;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="party")
    public Set<Charge> getCharges() {
        return this.charges;
    }
    
    public void setCharges(Set<Charge> charges) {
        this.charges = charges;
    }




}


