package org.anonymous.project;
// Generated 14.11.2015 00:32:01 by Hibernate Tools 4.3.1.Final


import java.sql.Blob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Party generated by hbm2java
 */
@Entity
@Table(name="PARTY"
    ,catalog="PUBLIC"
)
public class Party  implements java.io.Serializable {


     private int id;
     private int orga;
     private String name;
     private String description;
     private String shortname;
     private Blob icon;

    public Party() {
    }

	
    public Party(int id, int orga, String name, String shortname) {
        this.id = id;
        this.orga = orga;
        this.name = name;
        this.shortname = shortname;
    }
    public Party(int id, int orga, String name, String description, String shortname, Blob icon) {
       this.id = id;
       this.orga = orga;
       this.name = name;
       this.description = description;
       this.shortname = shortname;
       this.icon = icon;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="ORGA", nullable=false)
    public int getOrga() {
        return this.orga;
    }
    
    public void setOrga(int orga) {
        this.orga = orga;
    }

    
    @Column(name="NAME", nullable=false, length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="DESCRIPTION", length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="SHORTNAME", nullable=false, length=8)
    public String getShortname() {
        return this.shortname;
    }
    
    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

    
    @Column(name="ICON")
    public Blob getIcon() {
        return this.icon;
    }
    
    public void setIcon(Blob icon) {
        this.icon = icon;
    }




}


