package org.anonymous.project;
// Generated 14.11.2015 00:32:01 by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Property generated by hbm2java
 */
@Entity
@Table(name="PROPERTY"
    ,catalog="PUBLIC"
)
public class Property  implements java.io.Serializable {


     private int id;
     private Integer item;
     private Integer party;
     private Integer orga;
     private String akey;
     private String avalue;

    public Property() {
    }

	
    public Property(int id, String akey, String avalue) {
        this.id = id;
        this.akey = akey;
        this.avalue = avalue;
    }
    public Property(int id, Integer item, Integer party, Integer orga, String akey, String avalue) {
       this.id = id;
       this.item = item;
       this.party = party;
       this.orga = orga;
       this.akey = akey;
       this.avalue = avalue;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="ITEM")
    public Integer getItem() {
        return this.item;
    }
    
    public void setItem(Integer item) {
        this.item = item;
    }

    
    @Column(name="PARTY")
    public Integer getParty() {
        return this.party;
    }
    
    public void setParty(Integer party) {
        this.party = party;
    }

    
    @Column(name="ORGA")
    public Integer getOrga() {
        return this.orga;
    }
    
    public void setOrga(Integer orga) {
        this.orga = orga;
    }

    
    @Column(name="AKEY", nullable=false, length=64)
    public String getAkey() {
        return this.akey;
    }
    
    public void setAkey(String akey) {
        this.akey = akey;
    }

    
    @Column(name="AVALUE", nullable=false, length=64)
    public String getAvalue() {
        return this.avalue;
    }
    
    public void setAvalue(String avalue) {
        this.avalue = avalue;
    }




}


