package org.anonymous.project;
// Generated 27.11.2015 18:21:32 by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Property generated by hbm2java
 */
@Entity
@Table(name="PROPERTY"
    ,catalog="PUBLIC"
)
public class Property  implements java.io.Serializable {


     private int id;
     private Organisation organisation;
     private Item item;
     private Party party;
     private String akey;
     private String avalue;

    public Property() {
    }

	
    public Property(int id, String akey, String avalue) {
        this.id = id;
        this.akey = akey;
        this.avalue = avalue;
    }
    public Property(int id, Organisation organisation, Item item, Party party, String akey, String avalue) {
       this.id = id;
       this.organisation = organisation;
       this.item = item;
       this.party = party;
       this.akey = akey;
       this.avalue = avalue;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORGA")
    public Organisation getOrganisation() {
        return this.organisation;
    }
    
    public void setOrganisation(Organisation organisation) {
        this.organisation = organisation;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEM")
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PARTY")
    public Party getParty() {
        return this.party;
    }
    
    public void setParty(Party party) {
        this.party = party;
    }

    
    @Column(name="AKEY", nullable=false, length=64)
    public String getAkey() {
        return this.akey;
    }
    
    public void setAkey(String akey) {
        this.akey = akey;
    }

    
    @Column(name="AVALUE", nullable=false, length=64)
    public String getAvalue() {
        return this.avalue;
    }
    
    public void setAvalue(String avalue) {
        this.avalue = avalue;
    }




}


