-- sample data for anyway database

INSERT INTO "PUBLIC"."ORGANISATION" (ID,NAME,DESCRIPTION) VALUES (5,'timesheet','timesheet-system');
INSERT INTO "PUBLIC"."ORGANISATION" (ID,NAME,DESCRIPTION) VALUES (7,'any','anything');

INSERT INTO "PUBLIC"."PARTY" (ID,ORGA,NAME,DESCRIPTION) VALUES (1,5,'Max Mustermann',null);

INSERT INTO "PUBLIC"."ADDRESS" (ID,STREET,CODE,CITY,COUNTRY) VALUES (1,'Berliner Str.1','28376','Buxdehude','Deutschland');
INSERT INTO "PUBLIC"."ADDRESS" (ID,STREET,CODE,CITY,COUNTRY) VALUES (2,'Frankfurter Strasse 376','60988','Berlin','Deutschland');
INSERT INTO "PUBLIC"."ADDRESS" (ID,STREET,CODE,CITY,COUNTRY) VALUES (3,'Buxdehudener Strasse 5','10989','Hamburg','Deutschland');

INSERT INTO "PUBLIC"."COORDINATE" (ID,X,Y,Z) VALUES (1,47420775,10985401,0);
