-- correction on decimals (generated by architect)
alter table CHARGE alter column VALUE DECIMAL(8,2);
alter table ITEM alter column VALUE DECIMAL(8,2);
alter table DISCHARGE alter column VALUE DECIMAL(8,2);

-- sample data for anyway database

INSERT INTO "PUBLIC"."ORGANISATION" (ID,NAME,DESCRIPTION) VALUES (1,'any','anything');

INSERT INTO "PUBLIC"."PUBLIC"."CLASSIFICATION" (ID,VALUE,NAME,ICON) VALUES (1,1,'Standard',null);

INSERT INTO "PUBLIC"."ADDRESS" (ID,STREET,CODE,CITY,COUNTRY) VALUES (1,'Berliner Str.1','28376','Buxdehude','Deutschland');
INSERT INTO "PUBLIC"."ADDRESS" (ID,STREET,CODE,CITY,COUNTRY) VALUES (2,'Frankfurter Strasse 376','60988','Berlin','Deutschland');
INSERT INTO "PUBLIC"."ADDRESS" (ID,STREET,CODE,CITY,COUNTRY) VALUES (3,'Buxdehudener Strasse 5','10989','Hamburg','Deutschland');

INSERT INTO "PUBLIC"."COORDINATE" (ID,X,Y,Z) VALUES (1,47420775,10985401,0);
INSERT INTO "PUBLIC"."PUBLIC"."DIGITAL" (ID,LOCATION,NAME,VALUE) VALUES (1,1,'max.mustermann@web.de','max.mustermann@web.de');
INSERT INTO "PUBLIC"."PUBLIC"."ACCOUNT" (ID,NAME,BIC,IBAN) VALUES (1,'Einzug Max Mustermann','BICBANKXXX','BICBANKXXX0123456789');

INSERT INTO "CATEGORY" VALUES(1,'standard',NULL)
INSERT INTO "AREA" VALUES(1,1,'office',NULL)
INSERT INTO "TYPE" VALUES(1,1,'standard',NULL)
INSERT INTO "MISSION" VALUES(1,'standard',NULL,NULL)

INSERT INTO "PARTY" VALUES(1,1,1,'Max Mustermann',NULL,'MM',NULL)
INSERT INTO "ITEM" VALUES(1,1,1,1,'standard','2025-02-16 00:00:00',NULL,0.00,NULL,NULL)
