-- sample data for anyway database

INSERT INTO "PUBLIC"."ORGANISATION" (ID,NAME,DESCRIPTION) VALUES (1,'any','anything');

INSERT INTO "PUBLIC"."PARTY" (ID,ORGA,NAME,DESCRIPTION, SHORTNAME, ICON) VALUES (1,1,'Max Mustermann',null, 'MM', null);
INSERT INTO "PUBLIC"."PUBLIC"."CLASSIFICATION" (ID,VALUE,NAME,ICON) VALUES (1,1,'Standard',null);

INSERT INTO "PUBLIC"."ADDRESS" (ID,STREET,CODE,CITY,COUNTRY) VALUES (1,'Berliner Str.1','28376','Buxdehude','Deutschland');
INSERT INTO "PUBLIC"."ADDRESS" (ID,STREET,CODE,CITY,COUNTRY) VALUES (2,'Frankfurter Strasse 376','60988','Berlin','Deutschland');
INSERT INTO "PUBLIC"."ADDRESS" (ID,STREET,CODE,CITY,COUNTRY) VALUES (3,'Buxdehudener Strasse 5','10989','Hamburg','Deutschland');

INSERT INTO "PUBLIC"."COORDINATE" (ID,X,Y,Z) VALUES (1,47420775,10985401,0);
INSERT INTO "PUBLIC"."PUBLIC"."DIGITAL" (ID,LOCATION,NAME,VALUE) VALUES (1,1,'max.mustermann@web.de','max.mustermann@web.de');
INSERT INTO "PUBLIC"."PUBLIC"."ACCOUNT" (ID,NAME,BIC,IBAN) VALUES (1,'Einzug Max Mustermann','BICBANKXXX','BICBANKXXX0123456789');
