CREATE TABLE "CATEGORY" (
  "ID" INTEGER PRIMARY KEY AUTO_INCREMENT,
  "NAME" VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE "PRODUCT" (
  "ID" INTEGER PRIMARY KEY AUTO_INCREMENT,
  "NAME" VARCHAR(255) NOT NULL,
  "DESCRIPTION" VARCHAR(255) NOT NULL,
  "PICTURE" LONGBLOB,
  "PRICE" DECIMAL(12, 2) NOT NULL,
  "QUANTITY" INTEGER NOT NULL
);

CREATE TABLE "CATEGORY_PRODUCTS" (
  "PRODUCT" INTEGER NOT NULL,
  "CATEGORY" INTEGER NOT NULL,
  CONSTRAINT "PK_CATEGORY_PRODUCTS" PRIMARY KEY ("PRODUCT", "CATEGORY")
);

CREATE INDEX "IDX_CATEGORY_PRODUCTS" ON "CATEGORY_PRODUCTS" ("CATEGORY");

ALTER TABLE "CATEGORY_PRODUCTS" ADD CONSTRAINT "FK_CATEGORY_PRODUCTS__CATEGORY" FOREIGN KEY ("CATEGORY") REFERENCES "CATEGORY" ("ID");

ALTER TABLE "CATEGORY_PRODUCTS" ADD CONSTRAINT "FK_CATEGORY_PRODUCTS__PRODUCT" FOREIGN KEY ("PRODUCT") REFERENCES "PRODUCT" ("ID");

CREATE TABLE "USER" (
  "ID" INTEGER PRIMARY KEY AUTO_INCREMENT,
  "EMAIL" VARCHAR(255) UNIQUE NOT NULL,
  "PASSWORD" VARCHAR(255) NOT NULL,
  "CLASSTYPE" VARCHAR(255) NOT NULL,
  "NAME" VARCHAR(255),
  "COUNTRY" VARCHAR(255),
  "ADDRESS" VARCHAR(255)
);

CREATE TABLE "CARTITEM" (
  "ID" INTEGER PRIMARY KEY AUTO_INCREMENT,
  "QUANTITY" INTEGER NOT NULL,
  "CUSTOMER" INTEGER NOT NULL,
  "PRODUCT" INTEGER NOT NULL
);

CREATE INDEX "IDX_CARTITEM__CUSTOMER" ON "CARTITEM" ("CUSTOMER");

CREATE INDEX "IDX_CARTITEM__PRODUCT" ON "CARTITEM" ("PRODUCT");

ALTER TABLE "CARTITEM" ADD CONSTRAINT "FK_CARTITEM__CUSTOMER" FOREIGN KEY ("CUSTOMER") REFERENCES "USER" ("ID");

ALTER TABLE "CARTITEM" ADD CONSTRAINT "FK_CARTITEM__PRODUCT" FOREIGN KEY ("PRODUCT") REFERENCES "PRODUCT" ("ID");

CREATE TABLE "ORDER" (
  "ID" INTEGER PRIMARY KEY AUTO_INCREMENT,
  "STATE" VARCHAR(255) NOT NULL,
  "DATE_CREATED" DATETIME NOT NULL,
  "DATE_SHIPPED" DATETIME,
  "DATE_DELIVERED" DATETIME,
  "TOTAL_PRICE" DECIMAL(12, 2) NOT NULL,
  "CUSTOMER" INTEGER NOT NULL,
  "PROCESSED_BY" INTEGER
);

CREATE INDEX "IDX_ORDER__CUSTOMER" ON "ORDER" ("CUSTOMER");

CREATE INDEX "IDX_ORDER__PROCESSED_BY" ON "ORDER" ("PROCESSED_BY");

ALTER TABLE "ORDER" ADD CONSTRAINT "FK_ORDER__CUSTOMER" FOREIGN KEY ("CUSTOMER") REFERENCES "USER" ("ID");

ALTER TABLE "ORDER" ADD CONSTRAINT "FK_ORDER__PROCESSED_BY" FOREIGN KEY ("PROCESSED_BY") REFERENCES "USER" ("ID");

CREATE TABLE "ORDERITEM" (
  "QUANTITY" INTEGER NOT NULL,
  "PRICE" DECIMAL(12, 2) NOT NULL,
  "ORDER" INTEGER NOT NULL,
  "PRODUCT" INTEGER NOT NULL,
  CONSTRAINT "PK_ORDERITEM" PRIMARY KEY ("ORDER", "PRODUCT")
);

CREATE INDEX "IDX_ORDERITEM__PRODUCT" ON "ORDERITEM" ("PRODUCT");

ALTER TABLE "ORDERITEM" ADD CONSTRAINT "FK_ORDERITEM__ORDER" FOREIGN KEY ("ORDER") REFERENCES "ORDER" ("ID");

ALTER TABLE "ORDERITEM" ADD CONSTRAINT "FK_ORDERITEM__PRODUCT" FOREIGN KEY ("PRODUCT") REFERENCES "PRODUCT" ("ID")