-- correction on decimals (generated by architect)
alter table CHARGE alter column VALUE DECIMAL(8,2);
alter table ITEM alter column VALUE DECIMAL(8,2);
alter table DISCHARGE alter column VALUE DECIMAL(8,2);

INSERT INTO ORGANISATION VALUES (2,'timesheet','timesheet-system', null);
INSERT INTO CLASSIFICATION VALUES(2,2,'Entwicklung', null)
INSERT INTO CLASSIFICATION VALUES(0,2,'Ausfall', null)
INSERT INTO CATEGORY VALUES(1,'Standard', null)
INSERT INTO CATEGORY VALUES(2,'GPL', null)
INSERT INTO CATEGORY VALUES(3,'Gewerblich', null)
INSERT INTO AREA VALUES (1, 2, 'Redhat', null);
INSERT INTO AREA VALUES (2, 2, 'Eigen', null);

INSERT INTO TYPE (ID,AREA,NAME,ICON) VALUES (1,2,'Entwicklung',null);
INSERT INTO TYPE (ID,AREA,NAME,ICON) VALUES (2,2,'Krank',null);
INSERT INTO TYPE (ID,AREA,NAME,ICON) VALUES (3,2,'Urlaub',null);

-- Projekte
INSERT INTO ITEM (ID,ORGA,CLASS,TYPE,NAME,START,END,VALUE,DESCRIPTION,ICON) VALUES (3,2,1,1,'timesheet',{ts '2015-12-12 00:00:00'},null,8,null,null);
